version: '3'
services:
  db:
    build:
      # Linux/macOS:
      # context: "~/docker-webserver"
      # Windows:
      context: "C:\\docker-webserver"
      dockerfile: Dockerfile-db
    image: dbserver
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - webdev
    environment:
      MYSQL_ROOT_PASSWORD: root
  php:
    build:
      # Linux/macOS:
      # context: "~/docker-webserver"
      # Windows:
      context: "C:\\docker-webserver"
      dockerfile: Dockerfile-php
    image: phpserver
    ports:
      - "80:80" # HTTP connection
      - "443:443" # HTTPS connection
      - "3000:3000" # Node.js port
      - "5173:5173" # Vite dev server
      - "8000:8000" # Laravel port
      - "8025:8025" # Mailpit web UI
    volumes:
      - .:/var/www/site
    networks:
      - webdev
    command: ["/bin/sh", "-c", "/tmp/startup/db-config.py ${COMPOSE_PROJECT_NAME}-db-1 && apache2-foreground"]

networks:
  webdev:
    driver: bridge

volumes:
  dbdata:
